services:
  postgres:
    container_name: wave-postgres
    image: postgres:latest
    networks:
      - wavenet
    environment:
      - POSTGRES_USER=waveywaveysql
      - POSTGRES_PASSWORD=FtEn5W83nd7MUxElPjJAK8
      - POSTGRES_DB=wavenet
    volumes:
      - database:/var/lib/postgres
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready", "-d", "wavenet", "-U", "waveywaveysql" ]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s

  meilisearch:
    container_name: wave-meilisearch
    image: getmeili/meilisearch:v1.9
    environment:
      - http_proxy
      - https_proxy
      - MEILI_MASTER_KEY=7VIvUB_5CMnNr1XJ0jurD_O91GodcTwFcNNmRBHPtCY
      - MEILI_NO_ANALYTICS=${MEILI_NO_ANALYTICS:-true}
      - MEILI_ENV=${MEILI_ENV:-development}
      - MEILI_LOG_LEVEL
      - MEILI_DB_PATH=${MEILI_DB_PATH:-/data.ms}
    networks:
      - wavenet
    volumes:
      - meilisearch:/data.ms
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:7700" ]
      interval: 10s
      timeout: 5s
      retries: 5

  wavenet:
    container_name: wave-net-server
    networks:
      - wavenet
    ports:
      - 3000:3000
      - 50051:50051
    depends_on:
      - postgres
      - meilisearch
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      JWT_SECRET: WAVEYWEWVAEY
      MEILISEARCH_API_KEY: 7VIvUB_5CMnNr1XJ0jurD_O91GodcTwFcNNmRBHPtCY
      MEILISEARCH_API_URL: http://meilisearch:7700
      POSTGRES_URL: postgres://waveywaveysql:FtEn5W83nd7MUxElPjJAK8@postgres/wavenet
      GRPC_PORT: 50051
      WEB_PORT: 3000
    volumes:
      - /mnt/nasdrive/NASDrive/Tidal RIP/:/library
      - cache:/cache

volumes:
  database:
    name: wavenet-database-storage
  meilisearch:
    name: wavenet-meilisearch-storage
  cache:
    name: wavenet-cache-storage

networks:
  wavenet: