//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

pub mod prelude;

pub mod album;
pub mod artist;
pub mod artist_album;
pub mod artist_track;
pub mod artwork;
pub mod cover_art;
pub mod playlist;
pub mod playlist_track_item;
pub mod playlist_user;
pub mod track;
pub mod user;
pub mod user_likes;
