//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "playlist")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub title: String,
    pub description: Option<String>,
    pub created_at: DateTime,
    pub cover_source: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::playlist_track_item::Entity")]
    PlaylistTrackItem,
    #[sea_orm(has_many = "super::playlist_user::Entity")]
    PlaylistUser,
}

impl Related<super::playlist_track_item::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PlaylistTrackItem.def()
    }
}

impl Related<super::playlist_user::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PlaylistUser.def()
    }
}

impl Related<super::user::Entity> for Entity {
    fn to() -> RelationDef {
        super::playlist_user::Relation::User.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::playlist_user::Relation::Playlist.def().rev())
    }
}

impl ActiveModelBehavior for ActiveModel {}
