//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

pub use super::album::Entity as Album;
pub use super::artist::Entity as Artist;
pub use super::artist_album::Entity as ArtistAlbum;
pub use super::artist_track::Entity as ArtistTrack;
pub use super::playlist::Entity as Playlist;
pub use super::playlist_track_item::Entity as PlaylistTrackItem;
pub use super::playlist_user::Entity as PlaylistUser;
pub use super::track::Entity as Track;
pub use super::user::Entity as User;
pub use super::user_likes::Entity as UserLikes;
